+ env
+ sort
+ cd /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance
+ mkdir -pv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000002/000000
+ cd /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000002/000000
+ ln -sfnv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/namd_config/1.psf structure.psf
+ ln -sfnv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/namd_config/1.pdb structure.pdb
+ ln -sfnv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/namd_config/par .
+ sed s/RAND/11689/g /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/namd_config/md.conf
+ ln -sv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000001/000001/seg.coor ./parent.coor
+ ln -sv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000001/000001/seg.dcd ./parent.dcd
+ ln -sv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000001/000001/seg.vel ./parent.vel
+ ln -sv /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/traj_segs/000001/000000/seg.xsc ./parent.xsc
+ /Projects/dhardy/namd_builds/NAMD_3.0alpha11_Linux-x86_64-multicore-CUDA/namd3 +p2 md.conf
FATAL ERROR: Unable to open binary file parent.coor
+ python /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/westpa_scripts/calculatedistance.py
Traceback (most recent call last):
  File "/Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/westpa_scripts/calculatedistance.py", line 9, in <module>
    parent_universe = mda.Universe('structure.psf', 'seg.dcd')
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 365, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 565, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/lib/util.py", line 2495, in wrapper
    return func(self, *args, **kwargs)
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/DCD.py", line 137, in __init__
    self._file = DCDFile(self.filename)
  File "MDAnalysis/lib/formats/libdcd.pyx", line 220, in MDAnalysis.lib.formats.libdcd.DCDFile.__cinit__
  File "MDAnalysis/lib/formats/libdcd.pyx", line 307, in MDAnalysis.lib.formats.libdcd.DCDFile.open
OSError: DCD file does not exist
Exception ignored in: <function ReaderBase.__del__ at 0x7f21a6c0e560>
Traceback (most recent call last):
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/base.py", line 1403, in __del__
    self.close()
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/DCD.py", line 167, in close
    self._file.close()
AttributeError: 'DCDReader' object has no attribute '_file'
+ '[' /tmp/tmpspfmaw03 ']'
+ python /Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/westpa_scripts/dcd2pdb.py
Traceback (most recent call last):
  File "/Scr/arango/Sobolev-Hyun/1-WeightedEnsemble/2-MAB-AmB-Distance/westpa_scripts/dcd2pdb.py", line 8, in <module>
    current_universe = MDAnalysis.Universe('structure.psf', 'seg.dcd')
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 365, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/core/universe.py", line 565, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/lib/util.py", line 2495, in wrapper
    return func(self, *args, **kwargs)
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/DCD.py", line 137, in __init__
    self._file = DCDFile(self.filename)
  File "MDAnalysis/lib/formats/libdcd.pyx", line 220, in MDAnalysis.lib.formats.libdcd.DCDFile.__cinit__
  File "MDAnalysis/lib/formats/libdcd.pyx", line 307, in MDAnalysis.lib.formats.libdcd.DCDFile.open
OSError: DCD file does not exist
Exception ignored in: <function ReaderBase.__del__ at 0x7f6303a4dc60>
Traceback (most recent call last):
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/base.py", line 1403, in __del__
    self.close()
  File "/Projects/arango/anaconda3/envs/westpa2/lib/python3.10/site-packages/MDAnalysis/coordinates/DCD.py", line 167, in close
    self._file.close()
AttributeError: 'DCDReader' object has no attribute '_file'
+ cat seg.pdb
+ tail -n+5
+ grep ATOM
+ awk '{print $6, $7, $8}'
cat: seg.pdb: No such file or directory
+ rm -f md.conf parent.coor parent.dcd parent.vel parent.xsc seg.pdb seg.restart.coord seg.restart.coor.old seg.restart.vel seg.restart.vel.old seg.restart.xsc seg.restart.xsc.old structure.pdb structure.psf toppar
+ rm -f md.conf parent.coor parent.dcd parent.vel parent.xsc seg.pdb seg.restart.coord seg.restart.coor.old seg.restart.vel seg.restart.vel.old seg.restart.xsc seg.restart.xsc.old structure.pdb structure.psf toppar
